version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: kubik_previewable
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: kubik_previewable
      DATABASE_URL: postgres://postgres@db
      WEBPACKER_DEV_SERVER_HOST: webpack
      REDIS_URL: 'redis://redis:6379'
      LOCAL_HOST: ${LOCAL_HOST}
    volumes:
      - .:/kubik_previewable
      - ${SSH_PATH}:/home/.ssh
      - ./.docker/database.yml.docker:/kubik_previewable/test/dummy/config/database.yml
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
  webpack:
    build: .
    #command: ./bin/webpack-dev-server
    volumes:
      - .:/kubik_previewable
      - ./.docker/database.yml.docker:/kubik_previewable/test/dummy/config/database.yml
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
volumes:
  dbdata:

